### PR TITLE
Mark ServiceEntityRepository as lazy

### LINKED ISSUE #48666: Doctrine Manager not initiliazed in phpunit with php 8.2
### Symfony version(s) affected

6.2.0

### Description

I am running php 8.2 with symfony 6.2.
I have a KernelTestCase which tries to load a repository:
```
self::bootKernel();
$container = static::getContainer();
$container->get(MyRepository::class);
```
and this results in the following error:
```
Error: Call to a member function isTransient() on null

/app/vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:189
/app/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php:36
/app/src/Repository/MyRepository.php:36
/app/var/cache/publisher/test/ContainerJ3xN9um/Core_KernelTestDebugContainer.php:12920
/app/var/cache/publisher/test/ContainerJ3xN9um/Core_KernelTestDebugContainer.php:12056
/app/vendor/symfony/dependency-injection/Container.php:381
/app/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:40
/app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:191
/app/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:105
/app/vendor/doctrine/dbal/src/Connection.php:355
/app/vendor/doctrine/dbal/src/Connection.php:417
/app/vendor/doctrine/dbal/src/Connection.php:379
/app/vendor/doctrine/dbal/src/Connection.php:289
/app/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:140
/app/vendor/doctrine/doctrine-bundle/ConnectionFactory.php:119
/app/var/cache/publisher/test/ContainerJ3xN9um/Core_KernelTestDebugContainer.php:1872
/app/var/cache/publisher/test/ContainerJ3xN9um/Core_KernelTestDebugContainer.php:1889
/app/vendor/symfony/var-exporter/Internal/LazyObjectState.php:95
/app/vendor/symfony/var-exporter/LazyGhostTrait.php:174
/app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:862
/app/vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:50
/app/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:96
/app/vendor/symfony/http-kernel/Kernel.php:526
/app/vendor/symfony/http-kernel/Kernel.php:709
/app/vendor/symfony/http-kernel/Kernel.php:122
/app/vendor/symfony/framework-bundle/Test/KernelTestCase.php:73
/app/tests/app/publisher/Service/UserRoleRightServiceTest.php:20
```
`MyRepository.php:36` is just the constructor of the repository:
```
public function __construct(ManagerRegistry $registry)
{
    parent::__construct($registry, MyEntity::class);
}
```

If I `dump($manager);` in `vendor/doctrine/persistence/src/Persistence/AbstractManagerRegistry.php:187` I have the following output:
```
^ ContainerXmKqPiW\EntityManager_bad7396^ {#4157
  -config: null
  -conn: null
  -metadataFactory: null
  -unitOfWork: null
  -eventManager: null
  -proxyFactory: null
  -repositoryFactory: null
  -expressionBuilder: null
  -closed: false
  -filterCollection: null
  -cache: null
  -lazyObjectState: Symfony\Component\VarExporter\Internal\LazyObjectState^ {#15880
    +status: INITIALIZED_FULL
     …2
  }
}
```
This all worked previously with symfony 6.1 and php 8.1

### How to reproduce

Have an environment running with php 8.2 and symfony 6.2
Composer dependencies:
```
"phpunit/phpunit": "^9.0.0",
"symfony/phpunit-bridge": "6.2.*",
```

Have a unit test with:
```
self::bootKernel();
$container = static::getContainer();
$container->get(MyRepository::class);
```

run your test with `bin/phpunit`

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Replaces https://github.com/doctrine/DoctrineBundle/pull/1599
Fixes https://github.com/symfony/symfony/issues/48666
See https://github.com/symfony/symfony/issues/48666#issuecomment-1365845243 for details.

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
I just realized that lazy services are not compatible with final classes, so this might break some apps that aggressively make their repositories final.
That could be a reason to prefer #1599 instead.
Any opinion about the best way forward?

**Comment by ostrolucky** [comment]
Was that working before?

**Comment by nicolas-grekas** [comment]
Not really: the creation of the circular graph required double instantiations. This was mostly unnoticed but could still lead to strange situations where two different objects could be created (and passed to dependents) for the same service.

**Review by ostrolucky — COMMENTED** [review]
Can we have a test for this?

**Comment by ostrolucky** [comment]
That sounds to me like proxying final repositories before was working before, but it could result in different instances. Did I get it right? If this issue wasn't a downside of https://github.com/doctrine/DoctrineBundle/pull/1599, what was a downside of that solution?

**Comment by nicolas-grekas** [comment]
Proxying final classes works only when there is an interface to rely on. That's not the case for repositories so this never worked.
The downside of #1599 is the dependency on the trait, but I suppose that's a lesser downside than forbidding final classes (I didn't spot this before opening this one.)
I'm reopening #1599

**Comment by ostrolucky** [comment]
Ok let's go with https://github.com/doctrine/DoctrineBundle/pull/1599

**Pull request closed without merging**
