### PR TITLE
Allow twig ^3.0

### PR DESCRIPTION
**Pull request by schobner**
Hallo,

the DoctrineBundle prevent update twig 2 to twig 3. With this tiny change, it will be works. I have testet it local. All tests are green.

Greatings
Matthias Schobner

### CODE REVIEW

**Comment by stof** [comment]
This change is good to actually run tests against Twig 3. But note that `require-dev` is a root-only field, so it does **not** prevent updating Twig in your projects.

**Review by stof — APPROVED** [review]

**Comment by schobner** [comment]
The test fails because of symfony/http-kernel update at 5.2. 
I will add a pull request at DoctrineBundle:2.0. to solve this backwards.

`    "conflict": {
        ....
        "symfony/http-kernel": ">=5.2"`

Are you fine with this fixing idea?

**Comment by schobner** [comment]
The parameter `kernel.runtime_environment` was added in 5.2
[https://github.com/symfony/http-kernel/blob/5.x/CHANGELOG.md](https://github.com/symfony/http-kernel/blob/5.x/CHANGELOG.md)

**Comment by stof** [comment]
Conflicting with the next version of Symfony is not a fix. The testsuite should be fixed instead.

**Comment by schobner** [comment]
Ok, i will show if i can fix this

**Comment by schobner** [comment]
Can you please tag this branch/commit with 2.1.3

**Comment by ostrolucky** [comment]
Will do that later together with 2.2.0

**Comment by stof** [comment]
@schobner as I said above, this PR has **strictly no impact** on your ability to use Twig 3 in your own project

**Comment by schobner** [comment]
> @schobner as I said above, this PR has **strictly no impact** on your ability to use Twig 3 in your own project

Thank you for the explanation, i have understand it! Next tim i will know it.

**Pull request merged**
