### PR TITLE
Change type hint from `Registry` to `ManagerRegistry` in `ProfilerController`

### PR DESCRIPTION
**Pull request by priyadi**
The previous code breaks decorating `ManagerRegistry`. `ProfilerController` only uses `getConnection()` which is in the interface, so it is not a problem. And it is also the only remaining place in the package where `Registry` is used as the type hint instead of `ManagerRegistry`.

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]
LGTM

**Comment by ostrolucky** [comment]
Ideally we should use `\Doctrine\Persistence\ConnectionRegistry` here, since that method is defined there

**Comment by priyadi** [comment]
> Ideally we should use `\Doctrine\Persistence\ConnectionRegistry` here, since that method is defined there

changed `ManagerRegistry` to `ConnectionRegistry`

**Review by dmaicher — APPROVED** [review]

**Comment by dmaicher** [comment]
@ostrolucky do we consider this a bugfix for 2.11.x? or an improvement for 2.12.x?

**Comment by ostrolucky** [comment]
Let's do 2.12. I can't see how is this a bugfix

**Pull request merged**
