### PR TITLE
[WAIT] Added support for EntityMessageCollector

### PR DESCRIPTION
**Pull request by Nyholm**
This feature will allow you to register `EntityMessageCollector` as an event listener. This class will be merged into Symfony 4.4.

https://github.com/symfony/symfony/pull/28850

### CODE REVIEW

**Comment by alcaeus** [comment]
> The deprecation messages doesn't seem to be related with your PR [...]

No, those are already present in master. Just waiting for the Symfony Code Freeze before starting to fix them (again).

**Comment by alcaeus** [comment]
Rebased to fix the build and fixed phpcs issues already. I'm holding off on merging until https://github.com/symfony/symfony/pull/28850 is merged.

**Comment by alcaeus** [comment]
Note: https://github.com/symfony/symfony/pull/28850 has been closed in favour of https://github.com/symfony/symfony/pull/34310.

@Nyholm do you still plan to work on this?

**Comment by ostrolucky** [comment]
Silence looks like a no to me, let's close. Open new PR if something in upstream gets finalized and you would like to have a support in bundle.

**Pull request closed without merging**
