### PR TITLE
Fix php doc block

### PR DESCRIPTION
**Pull request by rosier**
Same as in the parent class

### CODE REVIEW

**Comment by alcaeus** [comment]
I would treat this as a bug and fix this in 1.10.x. @rosier could you rebase your PR to target the 1.10.x branch? Thanks!

**Comment by rosier** [comment]
Rebase on 1.10.x

**Comment by alcaeus** [comment]
Thank you! I'll work on fixing the build soon and merge afterwards.

**Comment by alcaeus** [comment]
Thanks @rosier!

**Pull request merged**
