### PR TITLE
added stacktraces for queries

### PR DESCRIPTION
**Pull request by dmecke**
I've added a stacktrace to the query profiler. This can help to find out why a specific query has been executed. This one depends on pull request https://github.com/doctrine/dbal/pull/535 in doctrine/dbal as it fetches the stacktrace information.

### CODE REVIEW

**Comment by stof** [comment]
closing as the DBAL PR has been rejected

**Comment by sustmi** [comment]
Just for reference, this feature is already available in Doctrine bundle: https://symfony.com/blog/new-in-doctrinebundle-1-11-0#store-backtraces-when-profiling-queries (PR: https://github.com/doctrine/DoctrineBundle/pull/954) .

You just need to enable it by setting `doctrine.dbal.profiling_collect_backtrace: true` (I set it to `'%kernel.debug%'` instead because it is the default value of `profiling` setting that this feature depends on).

Web search got me here and from this conversation it looks like it may not be available yet.

**Comment by stof** [comment]
Well, this conversation is from 2015. There are other PRs newer than that.

**Comment by sustmi** [comment]
I know that it's an old conversation but googling "

**Pull request closed without merging**
