### PR TITLE
Allow doctrine/persistence 2.x

### PR DESCRIPTION
**Pull request by fruitwasp**
* Allows doctrine/persistence 2.x
* Updates namespace of Doctrine persistence classes in tests.

### CODE REVIEW

**Comment by ostrolucky** [comment]
forward compatibility layer is present in 1.3, but no backwards compatibility layer is present in 2.0 AFAIK. We cannot suddenly start wiring incompatible classes, it will break projects that expect us wiring `common\persistence` compatible services.

**Comment by greg0ire** [comment]
Maybe create service with the old FQCN as service id, but the new FQCN as class, and deprecate those in favor of services with the new FQCN  as service id (and class)?

**Comment by ostrolucky** [comment]
I would rather drop support for persistence 1.x

**Comment by fruitwasp** [comment]
Agree on dropping support for 1.x. Apart from this, it requires support for 2.x in the symfony/doctrine-bridge too, as this bundle has a dependency on it. Will target master. https://github.com/symfony/symfony/compare/master...fruitwasp:doctrine-bridge your thoughts?

**Comment by ostrolucky** [comment]
That could work. Plan is that next minor doctrine-bundle release will by synced with next minor symfony release.

**Comment by greg0ire** [comment]
IMO if you don't add the `|| ^2.0` and require a recent enough version of persistence, you can contribute a lot of the changes in this PR to the stable branch, provided you add deprecated aliases with the old names.

**Comment by nusphere** [comment]
the actual release ob Symfony allow to install doctrine/persistence 2.x #1190 - this breaks some update processes

**Comment by stof** [comment]
Note that the title of this PR is not describing what it does. currently, it does not only add support for 2.x, but it also removes support for 1.x

**Comment by nicolas-grekas** [comment]
Keeping support for v1 would be great for the community.

**Comment by ostrolucky** [comment]
Maybe I'm missing something, but I don't see how can we solve issue I mentioned for persistence 2.x and at the same time keep support for v1

**Comment by greg0ire** [comment]
@ostrolucky what's wrong with https://github.com/doctrine/DoctrineBundle/pull/1181#issuecomment-649478220 ?

**Comment by ostrolucky** [comment]
Problem with that is people who inject `common\persistence\*` will get incompatible `persistence\*` like I mentioned earlier

**Comment by greg0ire** [comment]
>  it will break projects that expect us wiring common\persistence compatible services.

Are you thinking of projects that require `doctrine/common` but not (yet) `doctrine/persistence`? If yes, a solution would be to require `doctrine/common` 3 first. That would force said packages to express their dependency to `doctrine/persistence`, as mentioned in https://github.com/doctrine/common/releases/tag/3.0.0

**Comment by ostrolucky** [comment]
doctrine/common 3.0 requires doctrine/persistence 2.0, so end result is same - unsupported doctrine/persistence 1.x

**Comment by greg0ire** [comment]
Ah right indeed. @nicolas-grekas persistence 1 and 2 have very similar constraints, so I think it wouldn't actually be that big of a deal. We might want to require common 3 or at least conflict with anything below that to be on the safe side.

**Comment by stof** [comment]
`common\persistence\*` class names are class aliases for the new name in doctrine 1.3+.

If your code relies on these aliases, it is indeed not compatible with `doctrine/persistence` 2.x. But that's solved by requiring `doctrine/persistence` 1.x in that package (which should be in your dependencies anyway if you rely on it).
this is not a blocker for making DoctrineBundle compatible with both 1.x and 2.x (with the right lower bound on 1.x to ensure we have access to the new names)

**Comment by greg0ire** [comment]
> which should be in your dependencies anyway if you rely on it

That's the thing, you could be relying on `common\persistence\*` and have only a version of `doctrine/common` older than 2.10, that would be valid (although less and less likely I suppose). Even having something newer and still only have `"doctrine/common": ~2.10` is valid, having that namespace available is part of the contract of common 2.

**Comment by stof** [comment]
@greg0ire no. Having that namespace available is part of the contract of `doctrine/persistence 1.4+` as that's where they are implemented (the 1.4 version number is from my memory. Check the changelog to validate it). We could make DoctrineBundle conflict with older versions.

**Comment by greg0ire** [comment]
it's 1.3 and I think you are referring to the namespace w/o `Common`, which I wasn't referring to with "that namespace". So to sum up, you could:

- have package A require `doctrine/common` 2 and be a legit user of `Common\Persistence\*`
- require A in your project
- also require doctrinebundle

But I just noticed that `doctrine/common` 2 requires `doctrine/persistence` 1, so I would say we are in fact not at risk here 👍

**Comment by ostrolucky** [comment]
So what needs to be done?

**Comment by greg0ire** [comment]
Since the early versions of the BC layer are buggy, I'd use `^1.3.7 || ^2.0` as a constraint. [My comment about aliases](https://github.com/doctrine/DoctrineBundle/pull/1181#issuecomment-649478220) can be ignored I think, since the definitions changed in this PR are not public (right?). Also, not sure why the build fails so badly, maybe it's because of the constraint?

**Comment by ostrolucky** [comment]
Then @fruitwasp sorry about that but can you please change back constraint to allow persistence ^1.3.3?

**Comment by fruitwasp** [comment]
Travis coverage test failing seems to be unrelated?

**Comment by greg0ire** [comment]
I'm trying to address it in https://github.com/doctrine/DoctrineBundle/pull/1195 , it has to do with Symfony 5.2

**Comment by greg0ire** [comment]
@fruitwasp please retarget to 2.0.x as I asked in https://github.com/doctrine/DoctrineBundle/pull/1181#issuecomment-650140296, it should fix the build.

**Review by maxhelias — APPROVED** [review]

**Comment by greg0ire** [comment]
Woops sorry, @ostrolucky pointed out to me that the correct branch for this is 2.1.x

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @fruitwasp !

**Pull request merged**
