### PR TITLE
Use namespaced Twig

### PR DESCRIPTION
**Pull request by rosier**
Switch to namespaced classes

### CODE REVIEW

**Comment by xabbuh** [comment]
@alcaeus No, namespaced classes have been introduced much longer ago.

**Comment by alcaeus** [comment]
Oh, I must have missed that then. After taking another look, aliases have been added in Twig 1.34.0 for 1.x and 2.4.0 for 2.x, so those are the versions to be added in composer.json.

**Comment by rosier** [comment]
Just noticed that the twig deprecations make the tests also fail on php v7.x in the 1.10 branch.

Should I change the target to 1.10.x also?

**Comment by alcaeus** [comment]
Technically it would be possible, but I'm not sure about effectively changing the twig version requirements in a patch release, which would be necessary for this change. Instead, I'd like to change the builds to not fail on deprecations as we've done in other packages where this has become an issue in version branches.

**Comment by stof** [comment]
Well, Symfony itself already requires Twig versions shipping namespaced classes. So it is already impossible to install an older Twig version if you use a maintained version of Symfony.

**Comment by rosier** [comment]
Status: Needs Review

**Comment by rosier** [comment]
No problem. Thanks for the heads up.

**Pull request merged**
