### PR TITLE
Implement ContainerAwareInterface in ProfilerController

### PR DESCRIPTION
**Pull request by hacfi**
See #500 #501

Didn’t want to wait so created a new PR myself.

### CODE REVIEW

**Comment by xabbuh** [comment]
:+1:

**Comment by stloyd** [comment]
:+1:

**Comment by yurytolochko** [comment]
:+1:

**Comment by stof** [comment]
Thank you @hacfi.

**Comment by Ener-Getick** [comment]
Is it possible to have a patch release?

**Comment by Ener-Getick** [comment]
Ping this locks many bundle upgrade ...

**Comment by kimhemsoe** [comment]
@Ener-Getick Done

**Comment by Ener-Getick** [comment]
Thank you @kimhemsoe :smile:

**Pull request merged**
