### PR TITLE
Make tests compatible with symfony/http-kernel 5.2

### PR DESCRIPTION
**Pull request by schobner**
This should fix the error from here:

https://travis-ci.org/github/doctrine/DoctrineBundle/jobs/737975932
Related pull request to this pipeline: 
https://github.com/doctrine/DoctrineBundle/pull/1234

If this work, this should also merged to branch 2.1.x

### CODE REVIEW

**Comment by ostrolucky** [comment]
2.0.x is not maintained, retargetting to 2.1.x

**Comment by schobner** [comment]
> 2.0.x is not maintained, retargetting to 2.1.x

ok

**Comment by stof** [comment]
@ostrolucky what about having only a 2.x branch if we don't maintain multiple minor versions in parallel ?

**Comment by ostrolucky** [comment]
Feel free to bring this up on slack, this PR isn't best place to discuss that, I'm just reflecting how it is right now. But in short, I don't know enough to answer if that's a good idea.

**Comment by schobner** [comment]
I have merged the 2.1.x Branch into my branch and fixed the additional error in the CacheSchemaSubscriberTest

**Pull request merged**
