### PR TITLE
Allow `doctrine/persistence` 3

### PR DESCRIPTION
**Pull request by derrabus**

### CODE REVIEW

**Comment by derrabus** [comment]
The Psalm failure is unrelated: Psalm runs on PHP 7.1 in our CI while Persistence 3 requires PHP >= 7.2.

**Comment by derrabus** [comment]
I've tried locally and get the same failures on the 2.6.x branch. They're probably related to the ORM 2.12 and Persistence 2.5 releases.

**Comment by ostrolucky** [comment]
If you have time, would be greater to fix those, even though it might be unrelated to this PR

**Comment by derrabus** [comment]
Fixed in #1511

**Review by dmaicher — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
