### PR TITLE
Use `kernel.build_dir` by default for proxy dir and metadata cache

### PR DESCRIPTION
**Pull request by alexndlm**

### CODE REVIEW

**Comment by ostrolucky** [comment]
why?

**Comment by alexndlm** [comment]
> why?

https://github.com/symfony/symfony/blob/d867b1273343a4def8ce259d8aad966339faab4c/src/Symfony/Component/HttpKernel/KernelInterface.php#L116

**Comment by stof** [comment]
Given that the proxies and the metadata cache are directly derived from the source code and can be fully warmed up, I think this makes sense.
It makes things better for project wanting to deploy with a readonly file system, separating things that get generated during the build from things written in the writable cache folder (potentially treated as ephemeral).
Note that by default, Symfony does not separate the build directory from the cache directory. It requires an explicit opt-in.

**Review by ostrolucky — APPROVED** [review]

**Comment by stof** [comment]
However, seeing no changes in cache warmers looks a bit suspicious to me. I thought that cache warmers needed to use their second argument to properly warm up the build directory during the `cache:warmup` command.

**Comment by ostrolucky** [comment]
Change of `$phpArrayFile` in `DoctrineExtension` modifies this argument that's passed to `DoctrineMetadataCacheWarmer`. Do you think there is something else to do?

**Pull request merged**
