### PR TITLE
Skip resetting managers when proxy-manager is not installed

### LINKED ISSUE #1105: [BC break] Resetting a non-lazy manager service is not supported
> Updating doctrine/doctrine-bundle (1.12.2 => 1.12.4): Loading from cache

most of our tests now break with

```
LogicException: Resetting a non-lazy manager service is not supported. Declare the "doctrine.orm.default_entity_manager" service as lazy.
```

not much more info for now, but i wanted to report already.

If you need more info, let me know and i'll dive in :)

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Fixes #1105

### CODE REVIEW

**Review by alcaeus — APPROVED** [review]

**Review by stof — APPROVED** [review]

**Comment by alcaeus** [comment]
Thanks @nicolas-grekas!

**Comment by ro0NL** [comment]
@nicolas-grekas im afraid it doesnt solve our issue, after updating to 1.12.5 test still fail.

```
$ composer why ocramius/proxy-manager
doctrine/migrations  2.2.0  requires  ocramius/proxy-manager (^2.0.2)
```

:grin: 

here's a stack trace:

```
LogicException: Resetting a non-lazy manager service is not supported. Declare the "doctrine.orm.default_entity_manager" service as lazy.

/app/var/symfony-src/src/Symfony/Bridge/Doctrine/ManagerRegistry.php:53
/app/vendor/doctrine/persistence/lib/Doctrine/Persistence/AbstractManagerRegistry.php:235
/app/vendor/doctrine/doctrine-bundle/Registry.php:178
/app/var/symfony-src/src/Symfony/Component/HttpKernel/DependencyInjection/ServicesResetter.php:39
/app/var/symfony-src/src/Symfony/Component/HttpKernel/Kernel.php:113
/app/var/symfony-src/src/Symfony/Component/HttpKernel/Kernel.php:196
/app/var/symfony-src/src/Symfony/Component/HttpKernel/Client.php:65
/app/var/symfony-src/src/Symfony/Bundle/FrameworkBundle/Client.php:131
/app/var/symfony-src/src/Symfony/Component/BrowserKit/Client.php:404
/app/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php:124
/app/tests/functional/ApiTest.php:118
```

The `doctrine.orm.default_entity_manager` service is untouched on our side.

`ApiTest.php:118` evolves around

```
$client = ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase::createClient();
$client->disableReboot();
$client->request('GET', $iri); // L118
```

**Comment by nicolas-grekas** [comment]
Grrr :)
Could you please work on a fix? I think you're the best to find the proper fix at this stage...

**Comment by ro0NL** [comment]
@nicolas-grekas i'll dive in tomorrow... in general i think in our case it's related to stateful testing (disableReboot), so the reset is involved. I dont think it actually happens in web ... but i havent checked even :)

i figure the related PR is #1099

without knowing all the details... ultimately it's a BC break where it tries to reset it's own non-lazy service :thinking: 

cc @alcaeus

**Pull request merged**
