### PR TITLE
Allow Symfony 6.0

### PR DESCRIPTION
**Pull request by jderusse**
Same as #975

### CODE REVIEW

**Comment by greg0ire** [comment]
For this failure I don't have an explanation yet.

**Review by ostrolucky — CHANGES_REQUESTED** [review]
If you plan on continue doing this, then upper ranges are worthless. We could as well change all ^5.0 to >=5.0 and not bother with these PRs on each major.

Anyways, I don't like this. If you want us to test bundle with symfony 6.x that's fine, but we don't need to lie to consumers that we support it. Instead of changing composer.json for everyone, let's do it only during CI job.

**Comment by jderusse** [comment]
> For this failure I don't have an explanation yet.

I think it was because of missing leading `\` in `Doctrine\ORM\Proxy\Proxy`

> We could as well change all ^5.0 to >=5.0 and not bother with these PRs on each major.

I'm fine with that. tell me your preferences. 

> but we don't need to lie to consumers that we support it

I'm adding a job in the CI to test this new version.

> Instead of changing composer.json for everyone, let's do it only during CI job.

I'm not sure that possible. Could you give me a hint?

**Comment by ostrolucky** [comment]
Like this https://github.com/doctrine/DoctrineBundle/pull/735/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R38 I don't know why was this removed and replaced with this inflexible flex env variable.

But maybe you want people to allow to use bundle with symfony 6.x? Ok, then let's just change composer.json with >5.0.. But such change should go to 2.4.x branch IMO.

**Comment by jderusse** [comment]
well. what's you are pointing would allow DoctrineBundle to test Symfony 6. But it won't allow people that require DoctrineBundle to also use/test Symfony 6.

Anyway, I've added a test suite for Symfony 6, and the CI is green. We are not lying anymore when saying that DoctrineBundle is compatible with Symfony 6

**Review by Nyholm — APPROVED** [review]

**Review by nicolas-grekas — APPROVED** [review]
(a quick merge would be greatly appreciated, as that's a blocker on Symfony right now)

**Review by dmaicher — APPROVED** [review]

**Comment by ostrolucky** [comment]
Why is it a blocker for symfony?

**Comment by Nyholm** [comment]
The CI is red for all [6.0 PRs](https://github.com/symfony/symfony/milestone/26)

Here is a screenshot of just one CI job. Others fail for the same reason. 

Screenshot 2021-05-20 at 11 53 17

**Comment by ostrolucky** [comment]
Symfony doesn't need doctrine-bundle dependency since 2017, just remove it.

Also, not even Symfony 5.3 is out, I fail to see why are you focusing on 6.0 now.

**Comment by Nyholm** [comment]
@ostrolucky If we focus on this PR at the moment. 

Would you mind to review it and tell us if there is anything you would like to change on it or not?

**Comment by jderusse** [comment]
> Symfony doesn't need doctrine-bundle dependency since 2017, just remove it.
> 
> Also, not even Symfony 5.3 is out, I fail to see why are you focusing on 6.0 now.

Yes it does. https://github.com/symfony/symfony/blob/5.4/composer.json#L133

**Comment by ostrolucky** [comment]
> Yes it does. https://github.com/symfony/symfony/blob/5.4/composer.json#L133

I'm telling you it's not required to be there. It was added there in 2014 because of ACL tests in Symfony security bundle, which were dropped in 2017. Remove it.


> Would you mind to review it and tell us if there is anything you would like to change on it or not?

PR is fine. I'll merge it after doctrine-bundle dependency is removed from symfony/symfony.

**Comment by Nyholm** [comment]
> I'll merge it after doctrine-bundle dependency is removed from symfony/symfony.

Please merge it now. 
I'll make sure to not put you in this position in the future. It should always be with more planning/preparation, but ideally it would be in the way you describe: `doctrine-bundle` should not be a dependency of `symfony/symfony`.

**Comment by nicolas-grekas** [comment]
> I'll merge it after doctrine-bundle dependency is removed from symfony/symfony.

Please don't do that. That's coupling topics, bindings issues, basically making us hostage of your good will.

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/41333 and https://github.com/symfony/symfony/pull/41332 BTW.
That's good news if we can remove the bundle.

**Comment by ostrolucky** [comment]
I've recent experience that my suggestions were ignored after workarounds in doctrine-bundle were merged, so you must forgive me for stalling it now. Especially since nobody explained why is it critical to get 6.x working today and it cannot wait even a couple hours. I'll wait at least till CI builds in referenced PRs are finished then merge this.

**Review by ostrolucky — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you. 

I appreciate that you merged this PR. 

> I've recent experience that my suggestions were ignored after workarounds in doctrine-bundle were merged, so you must forgive me for stalling it now. 

Im sorry you feel that way. Please write an issue or reach out to me in a private chat if you want.

**Comment by nicolas-grekas** [comment]
> Also, not even Symfony 5.3 is out, I fail to see why are you focusing on 6.0 now.

I can answer that one: because we want a green CI :green_apple:

**Pull request merged**
