### PR TITLE
avoid trying to load nonexistent DoctrineTransportFactory class

### LINKED ISSUE #41727: Symfony 5.3: autoloader error with DoctrineTransportFactory
**Symfony version(s) affected**: >= 5.3.0 (just tested 5.3.0, 5.3.1, 5.3.2-dev#9485292)

**Description**
While running tests with Symfony 5.3 I'm getting [this error](https://travis-ci.org/github/craue/CraueGeoBundle/jobs/774461271#L609):
`RuntimeException: The autoloader expected class "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory" to be defined in file "/home/travis/build/craue/CraueGeoBundle/vendor/composer/../symfony/symfony/src/Symfony/Component/Messenger/Transport/Doctrine/DoctrineTransportFactory.php". The file was found but the class was not in it, the class name or namespace probably has a typo.`

I'm not actively using the Messenger component.

**How to reproduce**
Run the test suite of that bundle with latest dependencies.

**Possible Solution**
I _could_ work around the issue by removing `symfony/symfony` from the `require-dev` section in `composer.json` and explicitly defining the needed deps instead, but that would require further modifications to my test setup (to work with a range of Symfony versions) I'd like to avoid.

### PR DESCRIPTION
**Pull request by craue**
This fixes symfony/symfony#41727.

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by craue** [comment]
This instead would also do:
```diff
- if (! class_exists(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class)) {
+ if (! class_exists(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class, false)) {
```

**Comment by ostrolucky** [comment]
Build needs to be green. Please test if your second solution works in both scenarios, it's SA friendly

**Comment by nicolas-grekas** [comment]
> + if (! class_exists(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class, false)) {

I'm not sure this would, as it would not try to actually load the class and would rely on class loading order.

**Comment by craue** [comment]
I could only test if it's working in my scenario (to avoid the error), it does.

**Comment by nicolas-grekas** [comment]
OK, then I confirm this 2nd patch would break the logic when the package is found in vendor.

**Comment by craue** [comment]
Too bad. What about the failing SA then?

**Comment by ostrolucky** [comment]
Closing here, as this is a broken BC on Symfony side. Doctrine-bundle shouldn't have to update the code  just so it keeps working with next  minor symfony version. Please fix BC layer on Symfony side.

**Comment by ostrolucky** [comment]
Actually, just noticed code on symfony side didn't change since symfony 5.1, which is probably when we added class_exists, so it's our BC layer that was broken whole time

**Review by ostrolucky — CHANGES_REQUESTED** [review]
One solution which should be better is reversing the conditions. Default to new transport factory. If it doesn't exist, use legacy one.

**Comment by craue** [comment]
Like this?
```diff
- if (! class_exists(DoctrineTransportFactory::class)) {
-     // If symfony/messenger < 5.1
-     if (! class_exists(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class)) {
-         // Dont add the tag
-         return;
-     }
- 
-     $transportFactoryDefinition->setClass(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class);
- }
- 
- $transportFactoryDefinition->addTag('messenger.transport_factory');
+ if (class_exists(DoctrineTransportFactory::class)) {
+     $transportFactoryDefinition->addTag('messenger.transport_factory');
+ } elseif (class_exists(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class, false)) {
+     // symfony/messenger >= 5.1
+     $transportFactoryDefinition->setClass(\Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory::class);
+     $transportFactoryDefinition->addTag('messenger.transport_factory');
+ }
```

**Comment by ostrolucky** [comment]
yes, but without false flag

**Comment by craue** [comment]
> yes, but without false flag

Without it, I'd get the initial error again.

**Comment by ostrolucky** [comment]
I'm back to my first response: It's an issue on Symfony side. I've created https://github.com/symfony/symfony/issues/42303. As for what you can do, you can call `DebugClassLoader::disable()` in your test case, or stop using symfony/phpunit-bridge, which enables it

**Comment by craue** [comment]
Calling `DebugClassLoader::disable()` in my test case makes it pass but complain about

```
Remaining indirect deprecation notices (1)

  1x: Since symfony/messenger 5.1: The "Symfony\Component\Messenger\Transport\Doctrine\DoctrineTransportFactory"
class is deprecated, use "Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransportFactory" instead.
The Doctrine transport has been moved to package "symfony/doctrine-messenger" and will not be included by default
in 6.0. Run "composer require symfony/doctrine-messenger".
```

although I'm not actively using the messenger and cannot see a way to get rid of that deprecation notice.

**Comment by ostrolucky** [comment]
see referenced issue. stop using symfony/symfony

**Pull request closed without merging**
