### PR TITLE
deprecate all ORM proxy commands

### PR DESCRIPTION
**Pull request by dmaicher**
Closes https://github.com/doctrine/DoctrineBundle/issues/1524

List of all doctrine commands from this bundle as tested on one of my apps using this branch:

```
      doctrine:database:create                  Creates the configured database                                                                                    
      doctrine:database:drop                    Drops the configured database                                                                                      
      doctrine:query:sql                        Executes arbitrary SQL directly from the command line.                                                             
      doctrine:cache:clear-metadata             Clear all metadata cache of the various cache drivers                                                              
      doctrine:cache:clear-query                Clear all query cache of the various cache drivers                                                                 
      doctrine:cache:clear-result               Clear all result cache of the various cache drivers                                                                
      doctrine:cache:clear-collection-region    Clear a second-level cache collection region                                                                       
      doctrine:mapping:convert                  Convert mapping information between supported formats                                                              
      doctrine:schema:create                    Processes the schema and either create it directly on EntityManager Storage Connection or generate the SQL output  
      doctrine:schema:drop                      Drop the complete database schema of EntityManager Storage Connection or generate the corresponding SQL output     
      doctrine:ensure-production-settings       Verify that Doctrine is properly configured for a production environment                                           
      doctrine:cache:clear-entity-region        Clear a second-level cache entity region                                                                           
      doctrine:mapping:info                     Show basic information about all mapped entities                                                                   
      doctrine:cache:clear-query-region         Clear a second-level cache query region                                                                            
      doctrine:query:dql                        Executes arbitrary DQL directly from the command line                                                              
      doctrine:schema:update                    Executes (or dumps) the SQL needed to update the database schema to match the current mapping metadata             
      doctrine:schema:validate                  Validate the mapping files                                                                                         
      doctrine:mapping:import                   Imports mapping information from an existing database     
```

### CODE REVIEW

**Review by ostrolucky — APPROVED** [review]

**Comment by stof** [comment]
The `doctrine:query:dql` command is redefining the help text instead of inheriting it from the parent. Can you check why this was done ? Is the help text of the bundle better than the help text of the ORM ?

**Comment by stof** [comment]
This should probably also deprecate the proxy commands for DBAL commands. For now, you handle only ORM ones.

**Comment by dmaicher** [comment]
> The `doctrine:query:dql` command is redefining the help text instead of inheriting it from the parent. Can you check why this was done ? Is the help text of the bundle better than the help text of the ORM ?

ORM:
```
Executes arbitrary DQL directly from the command line.
``` 

Bundle:
```
The <info>%command.name%</info> command executes the given DQL query and
outputs the results:

<info>php %command.full_name% "SELECT u FROM UserBundle:User u"</info>

You can also optional specify some additional options like what type of
hydration to use when executing the query:

<info>php %command.full_name% "SELECT u FROM UserBundle:User u" --hydrate=array</info>

Additionally you can specify the first result and maximum amount of results to
show:

<info>php %command.full_name% "SELECT u FROM UserBundle:User u" --first-result=0 --max-result=30</info>
``` 

So yeah seems better :smile:

**Comment by stof** [comment]
I suggest improving the help in the ORM (without using the entity namespace feature that has been removed in doctrine/persistence 3.x)

**Comment by dmaicher** [comment]
@stof see https://github.com/doctrine/orm/pull/10233

**Comment by dmaicher** [comment]
@stof regarding

> This should probably also deprecate the proxy commands for DBAL commands. For now, you handle only ORM ones.

Which DBAL command are you referring to exactly?

From what I can tell all commands inside the `Command\Proxy` namespace are now deprecated.


Screenshot from 2022-11-15 17-03-21

**Comment by stof** [comment]
Actually, the deprecation of DBAL proxy commands was half-done already. For instance, `Doctrine\Bundle\DoctrineBundle\Command\Proxy\RunSqlDoctrineCommand` is marked as deprecated, but it is still used when running the command (unlike your change where you use the ORM commands directly for service definitions)

**Comment by dmaicher** [comment]
@stof I will do this for the DBAL command(s) separately. Ok?

**Comment by dmaicher** [comment]
@stof @ostrolucky actually this is done already for the DBAL command, right?

Checking 

https://github.com/doctrine/DoctrineBundle/commit/95c9daff56c0eba9a8df1838c46a63a52735dde0#diff-11eb636a4aa9dc6c6b58251b233250d85cb1b8c16ec5845574e7a5b4fd90ff42R105

I see that because of the changed command name `doctrine:query:sql` vs `dbal:run-sql` basically we now have both classes registered as services.

**Comment by ostrolucky** [comment]
yeah

**Pull request merged**
