### PR TITLE
fix: Prefer primary config over master.

### PR DESCRIPTION
**Pull request by prengerjarno**
Make sure the primary config gets used over the master so it uses the added options when PrimaryReadReplicaConnection is used. #1257

### CODE REVIEW

**Comment by ostrolucky** [comment]
New primary config was added in 2.2, so this is the branch this should point to

**Comment by prengerjarno** [comment]
@ostrolucky I'm sorry, its not the config, its the params. Both 'master' and 'primary' params are present to because of the BC support in doctrine/dbal's `MasterSlaveConnection`. In this case it should use the 'primary' params, but is using the 'master' which is missing the 'driver' option (because it only gets added to 'primary' in `PrimaryReadReplicaConnection::__construct`).

**Review by stof — APPROVED** [review]

**Comment by ostrolucky** [comment]
If DBAL is adding `driver` to primary only and not to master, that's a bug in DBAL's BC layer and you need to report issue there.

**Comment by stof** [comment]
@ostrolucky `->getParams` is an API marked as internal.

**Comment by ostrolucky** [comment]
Up to dbal 2.11 initiating connection with `master` would result in `getParams` giving you back array including `master['driver']` and then it was changed because in 2.11 it was marked internal and that's ok? That's not how BC works. Method cannot be broken in minor release like that and claim it's ok because it's internal now. It can be broken in 3.x, not in 2.x.

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
I managed to trigger a build.

**Comment by greg0ire** [comment]
Thanks @prengerjarno

**Pull request merged**
