### PR TITLE
Fix PHP 5.6+only syntax that breaks the Symfony CI

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Introduced in #855

### CODE REVIEW

**Comment by stof** [comment]
This change was indeed wrong due to the min PHP version supported by the bundle.

**Comment by Majkl578** [comment]
The commit message is wrong - `use function` is not 7.1-only syntax, it exists as of 5.6.

@kimhemsoe Can we just drop <7.1 support in master? It's been source of mutliple issues and confusion (last time [here](https://github.com/doctrine/DoctrineBundle/pull/853#discussion_r220539226), [here](https://github.com/doctrine/DoctrineBundle/pull/855#discussion_r220397344) and [here](https://github.com/doctrine/DoctrineBundle/pull/855#issuecomment-434115106)), it's really time.

**Comment by nicolas-grekas** [comment]
Commit message updated.

**Comment by kimhemsoe** [comment]
@nicolas-grekas Thanks

**Comment by nicolas-grekas** [comment]
@kimhemsoe thanks to you. We're back to green :)

**Comment by Ocramius** [comment]
Folks, this change is invalid: the fact that symfony mocks `method_exists` within the DoctrineBundle namespaces is already a nightmare.

This needs to be fixed downstream, not here.

**Comment by Ocramius** [comment]
Hmm, no, my comment was incorrect: this is because of PHP version support.

Sending a patch to finally put a tombstone on it, once and for all.

**Pull request merged**
