### PR TITLE
Update entity-listeners.rst

### PR DESCRIPTION
**Pull request by luciantugui**
code blocks are visible now

### CODE REVIEW

**Comment by Ocramius** [comment]
Thanks!

**Comment by xabbuh** [comment]
@luciantugui  @Ocramius You now have two code blocks and not the nice tabbed view the Symfony documentation uses everywhere else. Furthermore, due to the indentation, the code blocks are no rendered as blockquotes (see http://symfony.com/doc/master/bundles/DoctrineBundle/entity-listeners.html). Is that intended?

**Comment by luciantugui** [comment]
@xabbuh new [PR](https://github.com/doctrine/DoctrineBundle/pull/391)

**Comment by stof** [comment]
This should be reverted. It is breaking the doc on symfony.com, which is the place for which we intend to render it (github.com rendering of rST file is incomplete anyway)

**Comment by luciantugui** [comment]
@stof [this PR](https://github.com/doctrine/DoctrineBundle/pull/391) should fix it for both

**Comment by stof** [comment]
no it does not. Displaying different formats below each other is not what we want on symfony.com. It is not consistent.
I reverted the merge in https://github.com/doctrine/DoctrineBundle/commit/ff5eaef0d614a4040b6c0b28dc3935c5a940485b and changed the doc link in the readme in https://github.com/doctrine/DoctrineBundle/commit/0162e00821ff23e961efee7b88753b85f3722036

**Comment by luciantugui** [comment]
ok, sorry for removing configuration block, got it now, although it's still not rendered correctly: [entity listeners](http://symfony.com/doc/master/bundles/DoctrineBundle/entity-listeners.html)

as a side note, can [entity listeners](http://symfony.com/doc/master/bundles/DoctrineBundle/entity-listeners.html) be mentioned in the [cookbook entry](http://symfony.com/doc/current/cookbook/doctrine/event_listeners_subscribers.html) regarding event listeners and subscribers? thanks

**Comment by xabbuh** [comment]
> ok, sorry for removing configuration block, got it now, although it's still not rendered correctly: entity listeners

@luciantugui The documentation has not been regenerated since the last change.

> as a side note, can entity listeners be mentioned in the cookbook entry regarding event listeners and subscribers? thanks

Can you open a pull request or create an issue on the Symfony documentation repository?

**Comment by Ocramius** [comment]
@stof  sorry, thought this kind of separate view was intentional, so I didn't think too much about it before merging. Thanks for reverting :-)

**Pull request merged**
