### PR TITLE
fix issue with doctrine/dbal 2.11 and connection option

### PR DESCRIPTION
**Pull request by dmaicher**
See https://github.com/doctrine/DoctrineBundle/issues/1179#issuecomment-704930637

### CODE REVIEW

**Comment by stof** [comment]
The proper fix would be to wire the ConnectionProvider instead.

**Comment by dmaicher** [comment]
> The proper fix would be to wire the ConnectionProvider instead.

This is more a quick fix to make sure it works with dbal 2.11 until we have a proper fix including `ConnectionProvider`.

If you think we should not release this fix first then I can also close here. I don't mind :blush:

**Comment by ostrolucky** [comment]
Why are we again fixing doctrinebundle instead of fixing DBAL? DBAL broke this in in minor version, issue is on their side.

**Comment by dmaicher** [comment]
@ostrolucky not sure how to fix this on DBAL's side :confused: 

This fix is similar to your fix here https://github.com/doctrine/DoctrineBundle/commit/86d2469d6be06d55ad7b9e2f076f6942476f2e87

**Comment by stof** [comment]
@ostrolucky the issue here is that we were adding new options in a child class. This broke when upstreaming the option.
But I don't think DBAL can be considered responsible for that. If you want to allow child classes to add new command options in a BC way, you have to forbid DBAL from ever changing the available options (the same would be true regarding adding methods in a child class, and that's why Symfony excludes such possibility from safe changes in downstream code).

**Comment by stof** [comment]
And as DBAL 2.11 is released now, we should not do a weird hack to keep the DoctrineBundle feature working. We should use the new upstream feature instead.

**Comment by ostrolucky** [comment]
Yeah, after some more investigation I don't think we should hold DBAL accountable for this.

> If you want to allow child classes to add new command options in a BC way, you have to forbid DBAL from ever changing the available options

You are talking about what happened previously, in linked commit. What happened now is that DBAL added exception throw when connection is specified. But I don't personally stand behind opinion that adding exception throws is a BC break in general either.


> And as DBAL 2.11 is released now, we should not do a weird hack to keep the DoctrineBundle feature working. We should use the new upstream feature instead.

We will do that, but in 2.2. This is non trivial change which will also include deprecating our commands.

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
