### PR TITLE
Fix lowsest dep

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by stof** [comment]
why is there many changes not related to the title of the PR here ?

**Comment by mikeSimonson** [comment]
Thanks @guilhermeblanco . Do you know why composer keeps installing phpunit master ? even when I set ~4.6 like here https://github.com/doctrine/DoctrineBundle/pull/310

**Comment by mikeSimonson** [comment]
The last commit was just to make the tests pass and the tests failed only because they revealed that the composer requirement weren't good.

Is there something else that is a problem ? @stof

**Comment by stof** [comment]
But all the first commits in this PR have nothing to do with the title: ``Fix lowsest dep``

**Comment by mikeSimonson** [comment]
sorry I mixed up the PR.

The last commit was to fix #310 .
PR that I messed up a bit anyway.

**Pull request merged**
