### PR TITLE
[DoctrineBundle] remove doctrine.event_subscriber tag and replace by doctrine.event_listener tag

### PR DESCRIPTION
**Pull request by alli83**
Remove doctrine.event_subscribers tag in bundle and replace them with doctrine.event_listener tag.

following https://github.com/symfony/symfony/pull/49918

### CODE REVIEW

**Review by nicolas-grekas — APPROVED** [review]

**Comment by dmaicher** [comment]
What about those defined in xml config files? :thinking: 

https://github.com/search?q=repo%3Adoctrine%2FDoctrineBundle%20doctrine.event_subscriber&type=code

**Comment by alli83** [comment]
All doctrine schema subscribers are deprecated since 6.3 and are going to be removed and replaced by their respective doctrine schema listeners already present in xml config files if I'm not wrong.

**Review by dmaicher — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]

**Comment by ostrolucky** [comment]
Not sure if we should do this in patch release

**Comment by SenseException** [comment]
> Not sure if we should do this in patch release

True. This should target 2.10.x.

**Comment by alli83** [comment]
ok thanks  ! i rebase and update the targeted branch then

**Comment by dmaicher** [comment]
Thanks @alli83

**Pull request merged**
