### PR TITLE
Tying to fix the issue with hhvm

### PR DESCRIPTION
**Pull request by mikeSimonson**

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@guilhermeblanco To fix the build with hhvm, we can either way use this PR or remove the stability dev .

Is that right ? What's the best solution ?
@stof

**Comment by guilhermeblanco** [comment]
@mikeSimonson if you `~4.6` does it break?

**Comment by mikeSimonson** [comment]
yes because it's stil getting the code-coverage dev-master

**Comment by mikeSimonson** [comment]
I start to think that the best way would be to remove the stability dev otherwise we are going to end up having to pin all the dependency it uses

**Comment by guilhermeblanco** [comment]
Give it a shot and remove the `minimum-stability`... =)
IIRC, it was added to allow some specifics on doctrine/common a few months ago while we had deployed ORM and DBAL, but not Common

**Pull request closed without merging**
