### PR TITLE
Fix creating sqlite database

### LINKED ISSUE #482: Creating Sqlite db fails because of quotes on path.
Hi, 
last release seems to break sqlite database creation with command.
In CreateDatabaseDoctrineCommand.php there is something strange :)

```php
 // Need to get rid of _every_ occurrence of dbname from connection configuration and we have already extracted all relevant info from url
unset($params['dbname'], $params['path'], $params['url']);
$tmpConnection = DriverManager::getConnection($params);
$shouldNotCreateDatabase = $ifNotExists && in_array($name, $tmpConnection->getSchemaManager()->listDatabases());
// Only quote if we don't have a path
if (!isset($params['path'])) {
    $name = $tmpConnection->getDatabasePlatform()->quoteSingleIdentifier($name);
}
```
 
unset($params['path']) and just few lines later if(!isset($params['path'])) results in 
```php
(line 58) Doctrine\DBAL\Schema\SqliteSchemaManagerarray:2 [
  "driver" => "pdo_sqlite"
  "path" => ""/var/www/bps/app/sqlite.db""
]
```
Config:
```yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:  pdo_sqlite
                path:    %kernel.root_dir%/sqlite.db
                #memory: true
                charset: utf8
```

### PR DESCRIPTION
**Pull request by hason**
Fixes #482.

### CODE REVIEW

**Comment by j0k3r** [comment]
:+1: for this!

**Comment by KingCrunch** [comment]
Hi @hason 

Like I mentioned in #434, although it works I don't think it's the right approach to use the `path` from the URL (which in fact is the database name) to find, whether or not the database name should be quoted. Imo you should use `driver` to find out, whether or not SQLite is used. What do you think?

**Comment by emmanuelballery** [comment]
:+1: huge BC for us :/

**Comment by matteosister** [comment]
please merge this and tag a new release. Thanks.

**Comment by WouterJ** [comment]
:+1: This is breaking our CMF builds :(

**Comment by j0k3r** [comment]
ping @guilhermeblanco :)

**Comment by jimmycleuren** [comment]
:+1: please merge

**Comment by slashfan** [comment]
+1 for a tag thanks :)

**Comment by pawaclawczyk** [comment]
+1 for tag
ping @guilhermeblanco

**Comment by guilhermeblanco** [comment]
Done. =) https://github.com/doctrine/DoctrineBundle/releases/tag/1.6.1

**Comment by j0k3r** [comment]
@guilhermeblanco thanks !

**Pull request merged**
