### PR TITLE
fix well known schema filter blacklist tables

### PR DESCRIPTION
**Pull request by bendavies**
These tables were backwards.

### CODE REVIEW

**Comment by alcaeus** [comment]
@bendavies can you please take a look at the failing tests? Thanks!

**Comment by bendavies** [comment]
@alcaeus done. it would be better if the tests tested the services one by one, which would have caught this bug, but there we go.

**Comment by alcaeus** [comment]
> @alcaeus done. it would be better if the tests tested the services one by one, which would have caught this bug, but there we go.

Absolutely - do you want to make the change?

**Comment by bendavies** [comment]
sure

**Comment by bendavies** [comment]
@alcaeus done

**Comment by alcaeus** [comment]
Thanks @bendavies!

**Pull request merged**
