### PR TITLE
added DatabaseDriverFactory to be injectable

### PR DESCRIPTION
**Pull request by oleg-andreyev**
Case

```
[Doctrine\ORM\Mapping\MappingException]                                             
  Property "d" in "Contract" was already declared, but it must be declared only once
```

- Need to reverse-engineer table with columns "D" and "_D" as result they are both are mapped to "D" field.
- Cannot call "setFieldNameForColumn" to add custom mapping

### CODE REVIEW

**Comment by stof** [comment]
Given that this command is deprecated, I don't think we should add new extension points in it.

**Comment by oleg-andreyev** [comment]
Any alternative/replacement for this command?

**Comment by stof** [comment]
No. Reverse-engineering a database table to generate the doctrine mapping has been discouraged by the Doctrine core team since the beginning of the Doctrine 2 era. There is no replacement doing reverse-engineering (at least no official one, maybe someone created a maintained third-party package for that)

**Comment by oleg-andreyev** [comment]
Sad, but okay.
Thanks.

**Pull request closed without merging**
