### PR TITLE
Fix an issue were some commented type

### PR DESCRIPTION
**Pull request by mikeSimonson**
They were not marked as such if the mappingType array was
empty.

Sadly I don't see any way to test this right now.

### CODE REVIEW

**Comment by stof** [comment]
IMO, we should deprecate this entirely. Types can be marked as commented inside themselves as of DBAL 2.3 or 2.4 (I don't remember anymore), which is much better, because it does not require getting the platform early.

**Comment by mikeSimonson** [comment]
This is related to #618 
Do you think that the issue is somewhere else because apparently the user use a type class that is marked as using a comment.
The issue might be in the EnumBundle but I couldn't reproduce it despite very creative attempts.

**Comment by mikeSimonson** [comment]
@stof It still fixed a few test that were apparently not running for some reason.

**Comment by mikeSimonson** [comment]
@stof Maybe we can add a deprecation when https://github.com/doctrine/DoctrineBundle/blob/master/ConnectionFactory.php#L83 is reached ?

**Comment by stof** [comment]
is there really no failure in DBAL when a non-existent class name is used for a type ?

**Comment by mikeSimonson** [comment]
@stof I didn't really tried understanding how that test passed in past but I am guessing one way or another this part wasn't run as the error is from PHP itself.

**Comment by mikeSimonson** [comment]
@stof For the deprecation notice I suppose we also need to change this default config.
https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/Configuration.php#L100

If I do that I suppose I should wait for a 2.0 ?

**Pull request merged**
