### PR TITLE
Make ServiceEntityRepository lazy on Symfony 6.2+

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Best reviewed [ignoring whitespaces](https://github.com/doctrine/DoctrineBundle/pull/1599/files?w=1).
See https://github.com/symfony/symfony/issues/48666 for background.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Closing in favor of #1600

**Comment by nicolas-grekas** [comment]
Reopening as discussed in #1600

**Comment by ostrolucky** [comment]
tests should be fixed

**Comment by nicolas-grekas** [comment]
How can I tell psalm to ignore the missing trait?

**Comment by nicolas-grekas** [comment]
Tests are green but psalm+cs are red.
I'm going AFK for a week so won't be able to have a closer look before.
If anyone is up to finish the PR, don't hesitate!

**Comment by ostrolucky** [comment]
I'll fix CS + SA

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
