### PR TITLE
Register the Validator auto-mapping loader

### PR DESCRIPTION
**Pull request by dunglas**
The missing part of symfony/symfony#27735.

### CODE REVIEW

**Comment by alcaeus** [comment]
Sorry @dunglas, didn't see you already created a PR. TBH, I like the approach in #939 a lot better and have ported the test to that PR. Closing here.

**Comment by dunglas** [comment]
Wow I totally forgot about this one 🤭

**Comment by alcaeus** [comment]
You and me both 🤭

**Comment by avrahamm** [comment]
Hi Douglas,
regarding [Automatic validation](https://symfony.com/blog/new-in-symfony-4-3-automatic-validation):
https://symfony.com/blog/new-in-symfony-4-3-automatic-validation
I am sorry but I do not understand how to make it work.
I have symfony 4.3 application, currently create Entities,
really do not want to add Validator annotations manually.
Thanks!
Avraham

**Comment by alcaeus** [comment]
@avrahamm please use one of the [Symfony support resources](https://symfony.com/support) instead of reviving an old pull request. Thanks!

**Comment by avrahamm** [comment]
Sure.
Thanks

**Pull request closed without merging**
