### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by pgrimaud**
Hello,

This PR will fix : 

- 1 typo in `ConnectionFactory.php`
- 1 typo in `DependencyInjection/Configuration.php`

Cheers! :robot:

### CODE REVIEW

**Comment by greg0ire** [comment]
The build breaks because of https://github.com/squizlabs/PHP_CodeSniffer/issues/2937

**Comment by ostrolucky** [comment]
Apply to lower branch?

**Comment by SenseException** [comment]
@ostrolucky The docs only show [unmaintained and one upcoming version](https://www.doctrine-project.org/projects/doctrine-bundle.html). There was probably confusion about the target branch. A website config should be added to master in another PR.

Composer is showing `"dev-master": "2.0.x-dev"` on master while there is a 2.0.x branch. Am I correct that 2.0.x should be the target?

**Comment by ostrolucky** [comment]
We still maintain 1.12.x. I assume this patch fits there too? But indeed, we should fix website config. Anyways feel free to merge as is, this tiny change isn't blocker in my opinion.

**Comment by ostrolucky** [comment]
Yeah can't even rebase myself as target is protected, let's merge

**Pull request merged**
