### PR TITLE
Add doctrine:database:import command to load SQL files

### PR DESCRIPTION
**Pull request by mpdude**
There's already a command for that in Doctrine/DBAL.

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@mpdude Thanks

**Comment by stof** [comment]
This will break things when using an older DBAL version not having the ImportCommand. Please use DelegateCommand as parent class instead, which proxies commands through delegation instead (you will need to overwrite ``isEnabled``, as the DelegateCommand checks the ORM version while this is the DBAL version

**Comment by mpdude** [comment]
The `ImportCommand` was added in DBAL 2.0 and hardy any of the other commands does it that way, so...?

**Comment by stof** [comment]
oh, I thought it was a new feature for which support in the bundle is added now in the bundle. It was in fact an old feature not exposed here

**Comment by mikeSimonson** [comment]
@stof So this can be merged as his ?

**Comment by mpdude** [comment]
*bump*

Any ideas when we might get the next release?

**Comment by mikeSimonson** [comment]
@mpdude thanks

**Comment by mpdude** [comment]
Any idea when you might tag the next minor version?

**Pull request merged**
