### PR TITLE
Add missing return type to fixture file

### PR DESCRIPTION
**Pull request by DurandSacha**

### CODE REVIEW

**Comment by alcaeus** [comment]
Closing here: Adding a return type to a non-final, non-private method in a non-final class is a BC break and not suitable for a new minor release. We'll be adding return type hints in 3.0.

**Comment by ostrolucky** [comment]
This is ok to do for tests in same fashion as https://github.com/doctrine/DoctrineBundle/pull/1121 did

**Comment by alcaeus** [comment]
Sorry, didn’t see this was a test fixture 👍

**Comment by ostrolucky** [comment]
🤦‍♂ indeed

**Pull request closed without merging**
