### PR TITLE
Allow to use dbal logging middleware instead of deprecated SQLLogger

### LINKED ISSUE #1429: Wire a middleware for logging
Follows doctrine/dbal#4967

The way we currently use to wire a logger is deprecated in DBAL 3.2 and has been removed in DBAL 4. We should instead wire the new middleware.

### PR DESCRIPTION
**Pull request by l-vo**
Fixes #1429

### CODE REVIEW

**Comment by stof** [comment]
To me, there is no reason for having a configuration for that. The core loggers should be wired as middles rather than loggers on newer DBAL versions without any config change.

**Comment by ostrolucky** [comment]
like @stof said, this should work without change in configuration

**Comment by l-vo** [comment]
@stof @ostrolucky thank you for your feedbacks, the point is the logged message formats are not the same; for a basic query, with SQLLogger:
```
[2022-01-02T12:47:18.370397+00:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3, t0.version AS version_4 FROM product t0 [] []
```
and with logging middleware:
```
[2022-01-01T13:45:40.827235+00:00] doctrine.DEBUG: Executing query: SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3, t0.version AS version_4 FROM product t0 {"sql":"SELECT t0.id AS id_1, t0.name AS name_2, t0.price AS price_3, t0.version AS version_4 FROM product t0"} []
```

It might be a problem if one do parsing of these logs for some reason. It's why I suggest an opt-in for this change.

**Comment by ostrolucky** [comment]
I see. That change is fine, we don't provide BC promise for log format.

**Comment by l-vo** [comment]
Ok, so I'm going to remove the opt-in.

**Comment by ostrolucky** [comment]
Does this solve the deprecations we currently have? See https://github.com/doctrine/DoctrineBundle/runs/4681778064?check_suite_focus=true I am thinking if it wouldn't be better to remove definition of doctrine.dbal.logger completely, instead of only its arguments.

**Comment by l-vo** [comment]
No, it doesn't, removing these deprecations needs two steps, the second (#1431) is about the profiler and involve to modify Doctrine Bridge (IMHO). I can work on it after this one. We can't remove `doctrine.dbal.logger` now because it also does time measurements (stopwatch) for the profiler.

**Review by dmaicher — APPROVED** [review]
Seems good to me. Tested it on my project and only noticed the different log message format. Apart from that all works well.

Next step would be to replace the data collection part for the profiler then? Like `DebugStack` and `BacktraceLogger`?

**Comment by ostrolucky** [comment]
fair enough, let's merge it then

**Comment by r-martins** [comment]
It does not really fix the deprecation warnings, right? It just fixes if we add a middleware class. Am I right?
If yes, how do we do that?

**Comment by l-vo** [comment]
@r-martins Yes, this is a step to fix them since it involves changes on Symfony too. The changes on Symfony are now merged but a final step is still missing in DoctrineBundle. I'm working on it.

**Pull request merged**
