### PR TITLE
Support auto generate mode `FILE_NOT_EXISTS_OR_CHANGED`

### PR DESCRIPTION
**Pull request by ruudk**
See:
- https://github.com/doctrine/common/pull/938
- https://github.com/doctrine/common/releases/tag/3.2.0

### CODE REVIEW

**Comment by ostrolucky** [comment]
This is cosmetic change only, right? All of these changes seem to be comments only

**Comment by ruudk** [comment]
You are right. I somehow thought there was a check on it but it's just comments. 
Should we target this to 2.4.x?

**Review by ostrolucky — APPROVED** [review]

**Comment by ostrolucky** [comment]
2.4 would be fine too, but doesn't matter here much

**Comment by ruudk** [comment]
Ok, let's leave it for 2.5.x then. Thanks.

**Pull request merged**
