### PR TITLE
Fix cache compatibility with cache pools

### PR DESCRIPTION
**Pull request by ostrolucky**
Somehow I cannot trigger the issue via a test, help welcome there.

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I confirm this fixes the issue.

**Comment by StaffNowa** [comment]
I had the same issue :) Now works again :)

**Comment by ostrolucky** [comment]
@nicolas-grekas can you help with a test case? I wonder why this doesn't trigger the issue
```php
public function testCacheConfigUsingCachePools(): void
{
    $this->expectNotToPerformAssertions();
    (new class () extends TestKernel {
        public function registerContainerConfiguration(LoaderInterface $loader): void
        {
            parent::registerContainerConfiguration($loader);
            $loader->load(static function (ContainerBuilder $containerBuilder): void {
                $containerBuilder->loadFromExtension('framework', [
                    'cache' => [
                        'pools' => [
                            'doctrine.result_cache_pool' => ['adapter' => 'cache.app'],
                            'doctrine.system_cache_pool' => ['adapter' => 'cache.system'],
                        ],
                    ],
                ]);
                $containerBuilder->loadFromExtension(
                    'doctrine',
                    ['orm' => [
                        'query_cache_driver' => ['type' => 'service', 'id' => 'custom_cache_service'],
                        'result_cache_driver' => ['type' => 'pool', 'id' => 'doctrine.result_cache_pool'],
                    ]]
                );
                $containerBuilder->setDefinition(
                    'custom_cache_service',
                    (new Definition(DoctrineProvider::class))
                        ->setArguments([new Definition(ArrayAdapter::class)])
                        ->setFactory([DoctrineProvider::class, 'wrap'])
                );
            });
        }
    })->boot();
}

```

**Comment by dmaicher** [comment]
@ostrolucky this reproduces it for me 

```php
    public function testCacheConfigUsingCachePools(): void
    {
        (new class () extends TestKernel {
            public function registerContainerConfiguration(LoaderInterface $loader): void
            {
                parent::registerContainerConfiguration($loader);
                $loader->load(static function (ContainerBuilder $containerBuilder): void {
                    $containerBuilder->loadFromExtension('framework', [
                        'cache' => [
                            'pools' => [
                                'doctrine.result_cache_pool' => ['adapter' => 'cache.adapter.filesystem'],
                            ],
                        ],
                    ]);
                    $containerBuilder->loadFromExtension(
                        'doctrine',
                        ['orm' => [
                            'result_cache_driver' => ['type' => 'pool', 'pool' => 'doctrine.result_cache_pool'],
                        ]]
                    );
                });
            }
        })->boot();
    }
```

```diff
- 'result_cache_driver' => ['type' => 'pool', 'id' => 'doctrine.result_cache_pool'],
+ 'result_cache_driver' => ['type' => 'pool', 'pool' => 'doctrine.result_cache_pool'],

**Review by dmaicher — APPROVED** [review]

**Comment by ostrolucky** [comment]
Thanks @dmaicher, I'm tired today

**Pull request merged**
