### PR TITLE
Update entity-listeners.rst

### PR DESCRIPTION
**Pull request by luciantugui**
fixed indentation

### CODE REVIEW

**Comment by xabbuh** [comment]
@luciantugui I still don't see the reason to remove the configuration block.

**Comment by luciantugui** [comment]
@xabbuh I did this initially because the code blocks weren't visible on [github docs](https://github.com/doctrine/DoctrineBundle/blob/2dceacb658fea2691972c1c2c9a4c5085f68bdb5/Resources/doc/entity-listeners.rst)

**Comment by stof** [comment]
@luciantugui the goal is to have doc rendered properly on http://symfony.com/doc/master/bundles/DoctrineBundle/index.html, not on Github. So please revert this change

**Comment by luciantugui** [comment]
but with the latest PR it should be fine on both now, can't we have it?
Thanks

On Fri, Feb 13, 2015 at 10:20 AM, Christophe Coevoet <
notifications@github.com> wrote:

> @luciantugui <https://github.com/luciantugui> the goal is to have doc
> rendered properly on
> http://symfony.com/doc/master/bundles/DoctrineBundle/index.html, not on
> Github. So please revert this change
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/doctrine/DoctrineBundle/pull/391#issuecomment-74225741>
> .
>



-- 
*Lucian Tugui*

google/skype: tugui.lucian

DE: +49 (0) 160 97 53 54 05
RO: +40 (0) 736 07 21 88

**Comment by stof** [comment]
Closing because I reverted https://github.com/doctrine/DoctrineBundle/pull/390. We definetely want to use configuration blocks to use the tabbed display of configuration formats. I changed the link to the doc to point to symfony.com in https://github.com/doctrine/DoctrineBundle/commit/0162e00821ff23e961efee7b88753b85f3722036

**Pull request closed without merging**
