### PR TITLE
Add native return type to commands

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Similar to https://github.com/doctrine/collections/pull/269 and related PRs.
Should help fix related deprecations.

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by ostrolucky** [comment]
Why not adding real type declarations?

**Comment by nicolas-grekas** [comment]
> Why not adding real type declarations?

you mean we could because `@final`?

**Comment by ostrolucky** [comment]
Well all of them are final or deprecated, so yeah it's fine to have native type declarations from my POV

**Comment by nicolas-grekas** [comment]
Works for me, PR updated.

**Review by ostrolucky — APPROVED** [review]

**Pull request merged**
