### PR TITLE
Missing file in replacement of dballogger by debugmiddleware

### PR DESCRIPTION
**Pull request by l-vo**
Missing file in #1517

### CODE REVIEW

**Comment by ostrolucky** [comment]
@nicolas-grekas can you pls check the failure, looks like some issue with DI phpdumper

**Comment by l-vo** [comment]
@ostrolucky why do you think it's a problem with the phpdumper ?

**Comment by dmaicher** [comment]
> @ostrolucky why do you think it's a problem with the phpdumper ?

I guess @ostrolucky is referring to the [build fail ](https://github.com/doctrine/DoctrineBundle/runs/6801941885?check_suite_focus=true) which indeed looks like some compiled container syntax issues

**Review by dmaicher — APPROVED** [review]
I can confirm this fixes [the issue](https://github.com/doctrine/DoctrineBundle/pull/1517#issuecomment-1149023230) and the profiler is working again :+1:

**Comment by nicolas-grekas** [comment]
See https://github.com/symfony/symfony/pull/46628 for the fix for the dumped container.

**Comment by l-vo** [comment]
> > @ostrolucky why do you think it's a problem with the phpdumper ?
> 
> I guess @ostrolucky is referring to the [build fail ](https://github.com/doctrine/DoctrineBundle/runs/6801941885?check_suite_focus=true) which indeed looks like some compiled container syntax issues

Oh of course! I thought it was about my modification. Thank you for the clarification 🙂

**Pull request merged**
