### PR TITLE
Add .gitattributes

### PR DESCRIPTION
**Pull request by garak**
This is also fixing #639

### CODE REVIEW

**Comment by mikeSimonson** [comment]
@garak Thanks

**Comment by alcaeus** [comment]
I'm not sure this is a good idea. This will cause a severe difference between running `composer install --prefer-source` and `composer install --prefer-dist`. IMO it would be better to split up into a `lib` and `tests` folder as we do on many other repositories (and as #641 suggested). What do you think @mikeSimonson?

**Comment by garak** [comment]
What would be the problem with such difference?

**Comment by alcaeus** [comment]
For starters, the issue you linked above is only fixed for some people. People with source installs still have the test sources available in their autoloader.

**Comment by garak** [comment]
Ah OK, I didn't realize that. Anyway, the issue is still open

**Comment by Ocramius** [comment]
@alcaeus we do it on all other repos and it's fine. The tests are NOT public API anyway, so whoever is installing the package as a dependency shouldn't care about whether they are there or not.

**Comment by mikeSimonson** [comment]
Well the next steps are

- to reorganize the repo with the tests outside the rest of the src folder
- and the autoload-dev feature of composer.json

**Pull request merged**
