### PR TITLE
#1210: add different statements metric to the Web Profiler Toolbar

### LINKED ISSUE #1210: Add "different statements" field to Symfony Web Debug Toolbar
Copy of: https://github.com/symfony/symfony/issues/38158

**Description**  
The Symfony Web Debug Toolbar is a powerful tool. Whenever a dev sees a colored section it starts to fear what it has potentially broken.

The Doctrine section is very useful as it shows the number of queries and the query time. If something goes wrong it became red/yellow and the dev is ready to detect what/where is the problem.
This section could be better if it also takes into account the __different statements__ count (that is already shown in the dedicated Symfony profiler page).

This information is useful to detect repeated queries that potentially impact performances. It could be also a detector for N+1 queries created due to a Doctrine bug.

**Example**  
The "different statements" information could be placed into the div that appears on mouse hover (as in the image below)
proposal

To have a fast detection of repeated queries, the Doctrine section of the toolbar could be colored with orange/yellow (the alert color) when the count of "different statements" is less than the count of "database queries".

### PR DESCRIPTION
**Pull request by lomby92**
Resolve #1210

### CODE REVIEW

**Review by ostrolucky — APPROVED** [review]

**Comment by greg0ire** [comment]
#1216 has been merged, let's restart the build.

**Comment by ostrolucky** [comment]
you would have to rebase

**Comment by greg0ire** [comment]
I don't understand why but it looks like you're right… I mean the new build should be run on the result of the merge of this commit and the current master, shouldn't it?

**Comment by ostrolucky** [comment]
nope

**Comment by greg0ire** [comment]
Weird… I will rebase.

**Comment by greg0ire** [comment]
Actually, it's not a normal checkout, the build is run on ae1a88587befd8880bc5cbdf19b7f12389244b85

**Comment by greg0ire** [comment]
Oh but the issue is not the same as before!

**Comment by greg0ire** [comment]
https://github.com/doctrine/DoctrineBundle/pull/1216 was not enough to fix the build, I will work on that.

**Comment by greg0ire** [comment]
Please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`lomby92@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @lomby92 !

**Comment by lomby92** [comment]
Thank you too!

**Pull request merged**
