### PR TITLE
fix BC break for removed service alias

### PR DESCRIPTION
**Pull request by dmaicher**
Fixes https://github.com/doctrine/DoctrineBundle/issues/1201

### CODE REVIEW

**Comment by NicoHaase** [comment]
Out of curiosity: is this a long-term fix, as in: we can expect that this service is kept longer, or will this be removed again in nearer future?

**Comment by dmaicher** [comment]
> Out of curiosity: is this a long-term fix, as in: we can expect that this service is kept longer, or will this be removed again in nearer future?

I think we should keep this alias as long as we support `doctrine/persistence < 2.0`. What do you think @ostrolucky ?

**Review by maxhelias — APPROVED** [review]

**Comment by nicolas-grekas** [comment]
A quick release would be much appreciated, we're getting the same report on many repos.

**Review by alcaeus — APPROVED** [review]

**Comment by alcaeus** [comment]
Merged and released. Thanks @dmaicher.

**Comment by NicoHaase** [comment]
> Should this "just fix everything that broke" ? Im between a rock and a hard place at the moment and cannot resolve it.

What does that mean? Is there any specific problem you are facing?

**Comment by PhilETaylor** [comment]
Sorry, should have put more work in before opening my mouth, Im debugging in smaller steps now to see if I can actually find anything helpful or if Im just an idiot... large project... 

I think my issue is to do with doctrine/persistence upgrade to 2.0.0 form 1.3.8 ... so ignore me totally for now :) sorry.

**Comment by PhilETaylor** [comment]
ok my problem is that FOSUser is showing its age, can't wait to dump it, and its not compatible with doctrine/persistence: 2.0.0 or  doctrine/common: 3.0.2 (not sure which yet) - so best just ignore me here :) sorry.

>Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given, called in /tmp/app/cache/Container0xAwrXe/configApp_KernelDevDebugContainer.php on line 3439

**Comment by ostrolucky** [comment]
> I  think we should keep this alias as long as we support doctrine/persistence < 2.0. What do you think @ostrolucky ?

Yep

**Comment by greg0ire** [comment]
I guess we should [deprecate one in favor of the other](https://symfony.com/blog/new-in-symfony-4-3-deprecating-service-aliases). Not sure under which conditions exactly the new service is available/usable. It seems to be defined all the time, so… no condition?

**Comment by ostrolucky** [comment]
Users get deprecations when using common\persistence classes already, I don't think we need to do more there. They know they shoiuld not use them. In some future version of bundle that will drop support doctrine/common 1.x we will just also drop old aliases. By requiring doctrine/common 2.x we will guarantee nobody can use old classes anymore, hence also service aliases.

**Pull request merged**
