### PR TITLE
Support for 'url' parameter in config

### PR DESCRIPTION
**Pull request by dzuelke**
Supported since Doctrine 2.5.0 :)

### CODE REVIEW

**Comment by Ocramius** [comment]
Assigning @kimhemsoe for review/merge

**Comment by dzuelke** [comment]
Well this works and is pretty trivial, @Ocramius, but the real issue is that tests are still failing due to unrelated version conflicts, even on master, and there's no solution and I haven't figured it out yet (I saw you closed the doctrine/doctrine2#1237 PR that attempted to fix this). Should I spin that off into its own bug report?

**Comment by deeky666** [comment]
@dzuelke those unrelated test failures are fine for now. I already open a PR https://github.com/doctrine/DoctrineBundle/pull/364 that deals with this issue, so no further action necessary here atm.
Otherwise looking good so far, despite it is missing some trivial tests.

**Comment by dzuelke** [comment]
Should I put the tests into `DoctrineExtensionTest` or somewhere else, @deeky666 ?

**Comment by stof** [comment]
I merged the Pr fixing the testsuite. Can you rebase your branch to rerun the testsuite with the fix ?

**Comment by stof** [comment]
Thanks @dzuelke.

**Pull request closed without merging**
