### PR TITLE
Remove deprecated functionality from DoctrineCommand

### PR DESCRIPTION
**Pull request by derrabus**
Since the master branch is 2.0 now, this code can be removed, right? 😃

### CODE REVIEW

**Comment by greg0ire** [comment]
#1025 should fix the build

**Comment by alcaeus** [comment]
Thanks to both of you. I'll take care of #1025 and this later today to fix the build (hopefully once and for all)

**Comment by derrabus** [comment]
@greg0ire Actually, #1016 would fix the red build, but it hasn't been merged up to master yet.

**Comment by alcaeus** [comment]
Thanks @derrabus!

**Pull request merged**
