### PR TITLE
Wiring of the new PropertyAccessExtractor

### PR DESCRIPTION
**Pull request by dunglas**
Wiring for symfony/symfony#31486.

### CODE REVIEW

**Comment by alcaeus** [comment]
LGTM. @dunglas can you fix the coding style error?

```
FILE: DependencyInjection/DoctrineExtension.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 799 | ERROR | [x] Use early exit to reduce code nesting.
     |       |     (SlevomatCodingStandard.ControlStructures.EarlyExit.EarlyExitNotUsed)
--------------------------------------------------------------------------------
```

**Comment by dunglas** [comment]
Actually, for this specific case, it just increases the cyclomatic complexity. But done in another commit.

**Comment by alcaeus** [comment]
I agree there - this is an edge case in the sniff that I don’t like either. I’ll see if we can update the coding standard or fix the sniff.

**Comment by dunglas** [comment]
It has been discussed here: https://github.com/slevomat/coding-standard/issues/371#issuecomment-401648617

**Comment by alcaeus** [comment]
I've changed the base to 1.11, but this is good to go. Thanks for the fix @dunglas!

**Pull request merged**
